### ISSUE TITLE
win-x64 version not working

### ISSUE THREAD

**Issue by Feathered-Serpent** [SabreTools/BinaryObjectScanner#287]
Downloaded  BinaryObjectScanner_3.1.0_net8.0_win-x64_release.zip and every file I want to test, even the Test.exe itself, causes in a file created called "exception-(timestamp).txt"

Example:
```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.




   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at BinaryObjectScanner.Handler.InitCheckClasses[T](Assembly assembly)
   at BinaryObjectScanner.Handler.InitCheckClasses[T]()
   at BinaryObjectScanner.Handler.get_PathCheckClasses()
   at BinaryObjectScanner.Handler.HandlePathChecks(String path, IEnumerable`1 files)
   at BinaryObjectScanner.Scanner.GetProtections(List`1 paths)
   at BinaryObjectScanner.Scanner.GetProtections(String path)
   at Test.Protector.GetAndWriteProtections(Scanner scanner, String path)
System.TypeLoadException
System.TypeLoadException
System.TypeLoadException
System.TypeLoadException

```

Using BinaryObjectScanner_3.1.0_net8.0_win-x86_release.zip works flawlessly. This one has a few DLLs inside, which the x64 version does not. Is there the problem?

**Comment by mnadareski** [comment]
Interesting that this doesn't seem to happen in the untargeted build. I'm going to have to take a look at this a bit deeper to see why building for `win-x64` is causing this issue.
